site_name: NSI
theme:
  name: material
  language: fr
  palette:
    primary: green
site_url: https://sibylleginger.github.io
nav:
  - 'Algorithmes':
    - 'Algorithmes de tris':
      - 'Cours': 'test'
      - 'TP' : 'TP tris_correction.md'
      - 'Révision' : 'test'
  - 'Partie 2':
    - "C4 : entier positif":
      - 'Cours': 'test'
      - 'Activité' : 'test'
      - 'Révision' : 'test'
    - "Booléens":
      - 'Cours': 'booleens.md'
      - 'Activité' : 'test'
      - 'Révision' : 'test'
