site_name: NSI

theme:
  features:
    - navigation.tabs
    - navigation.indexes
  name: material
  language: fr
  palette:
    primary: green
site_url: https://sibylleginger.github.io
nav:
  - 'Algorithmes':
    - 'algo/index.md'
    - 'Algorithmes de tris':
      - 'Cours': 'TP tris_correction.md'
      - 'TP' : 'TP tris_correction.md'
      - 'Révision' : 'test'
  - 'Types de base':
    - 'types_bases/index.md'
    - "Booléens":
      - 'Cours': 'types_bases/booleens.md'
      - 'TP' : 'types_bases/TP conversion bases.md'
      - 'Révision' : 'test'
